
Wymagania.
===============
Aby zbudowaæ jabber-gg-transport potrzeba:

	- glib (http://www.gtk.org/)
		Przetestowane z glib-1.2.10
	
	- libgg (czê¶æ EKG, http://dev.null.pl/ekg/)
		Prawdopodobnie potrzebny bêdzie snapshot z CVS
		Przetestowane ze snapshotem 20020223


Kompilacja
==============
Prosta jak w przypadku wiêkszo¶ci projektów OS:

	./configure
	make

Mo¿na u¿yæ opcji configure "--sysconfdir=", aby ustawiæ katalog z plikiem konfiguracyjnym,
lub "--disable-debug", aby wy³±czyæ kod "odpluskwiaj±cy".

